const CARRIER_FORM = {
  step1: {
    name: 'Carrier Information',
    groups: {
      contact_information: {
        name: 'Contact Information',
        subgroup: null,
        data: {
          company_name: {
            name: 'Carrier Name',
            type: 'text',
            value: '',
            error: false,
            required: true,
          },
          contact_name: {
            name: 'Contact Name',
            type: 'text',
            value: '',
            error: false,
            required: true,
          },
          contact_number: {
            name: 'Contact Number',
            type: 'numeric',
            value: '',
            error: false,
            required: true,
          },
          email: {
            name: 'E-mail',
            type: 'email',
            value: '',
            error: false,
            required: true,
          },
          carrier_state: {
            name: 'Carrier State',
            type: 'select',
            value: '',
            error: false,
            required: true,
            optionLabel: 'name',
            optionValue: 'name',
            arrayData: [
              { name: 'Alabama', abbreviation: 'AL' },
              { name: 'Alaska', abbreviation: 'AK' },
              { name: 'Arizona', abbreviation: 'AZ' },
              { name: 'Arkansas', abbreviation: 'AR' },
              { name: 'California', abbreviation: 'CA' },
              { name: 'Colorado', abbreviation: 'CO' },
              { name: 'Connecticut', abbreviation: 'CT' },
              { name: 'Delaware', abbreviation: 'DE' },
              { name: 'Florida', abbreviation: 'FL' },
              { name: 'Georgia', abbreviation: 'GA' },
              { name: 'Hawaii', abbreviation: 'HI' },
              { name: 'Idaho', abbreviation: 'ID' },
              { name: 'Illinois', abbreviation: 'IL' },
              { name: 'Indiana', abbreviation: 'IN' },
              { name: 'Iowa', abbreviation: 'IA' },
              { name: 'Kansas', abbreviation: 'KS' },
              { name: 'Kentucky', abbreviation: 'KY' },
              { name: 'Louisiana', abbreviation: 'LA' },
              { name: 'Maine', abbreviation: 'ME' },
              { name: 'Maryland', abbreviation: 'MD' },
              { name: 'Massachusetts', abbreviation: 'MA' },
              { name: 'Michigan', abbreviation: 'MI' },
              { name: 'Minnesota', abbreviation: 'MN' },
              { name: 'Mississippi', abbreviation: 'MS' },
              { name: 'Missouri', abbreviation: 'MO' },
              { name: 'Montana', abbreviation: 'MT' },
              { name: 'Nebraska', abbreviation: 'NE' },
              { name: 'Nevada', abbreviation: 'NV' },
              { name: 'New Hampshire', abbreviation: 'NH' },
              { name: 'New Jersey', abbreviation: 'NJ' },
              { name: 'New Mexico', abbreviation: 'NM' },
              { name: 'New York', abbreviation: 'NY' },
              { name: 'North Carolina', abbreviation: 'NC' },
              { name: 'North Dakota', abbreviation: 'ND' },
              { name: 'Ohio', abbreviation: 'OH' },
              { name: 'Oklahoma', abbreviation: 'OK' },
              { name: 'Oregon', abbreviation: 'OR' },
              { name: 'Pennsylvania', abbreviation: 'PA' },
              { name: 'Rhode Island', abbreviation: 'RI' },
              { name: 'South Carolina', abbreviation: 'SC' },
              { name: 'South Dakota', abbreviation: 'SD' },
              { name: 'Tennessee', abbreviation: 'TN' },
              { name: 'Texas', abbreviation: 'TX' },
              { name: 'Utah', abbreviation: 'UT' },
              { name: 'Vermont', abbreviation: 'VT' },
              { name: 'Virginia', abbreviation: 'VA' },
              { name: 'Washington', abbreviation: 'WA' },
              { name: 'West Virginia', abbreviation: 'WV' },
              { name: 'Wisconsin', abbreviation: 'WI' },
              { name: 'Wyoming', abbreviation: 'WY' },
            ],
          },
          carrier_city: {
            name: 'Carrier City',
            type: 'text',
            value: '',
            error: false,
            required: true,
          },
          carrier_street: {
            name: 'Carrier Street',
            type: 'text',
            value: '',
            error: false,
            required: true,
          },
          carrier_zip: {
            name: 'Carrier Zip',
            type: 'text',
            value: '',
            error: false,
            required: true,
          },
          us_dot: {
            name: 'US DOT #',
            type: 'text',
            value: '',
            error: false,
            required: true,
          },
          website: {
            name: 'Website',
            type: 'text',
            value: '',
            error: false,
            required: false,
          },
          describe: {
            name: 'Describe your Company',
            type: 'text',
            value: '',
            error: false,
            required: false,
            multiline: true,
          },
        },
      },
    },
  },
  step4: {
    name: 'Additional information',
    groups: {
      compensation_information: {
        name: 'Compensation Information',
        subgroup: null,
        data: {
          how_frequent: {
            name: 'How frequent?',
            type: 'select',
            value: '',
            error: false,
            required: true,
            optionLabel: 'name',
            optionValue: 'name',
            arrayData: [{ name: 'Weekly' }, { name: 'Other' }],
          },
          what_day: {
            sibling_radio: 'how_frequent',
            sibling_radio_value: 'Weekly',
            name: 'What day is payday?',
            type: 'select',
            value: '',
            error: false,
            required: true,
            optionLabel: 'name',
            optionValue: 'name',
            arrayData: [
              { name: 'Monday' },
              { name: 'Tuesday' },
              { name: 'Wednesday' },
              { name: 'Thursday' },
              { name: 'Friday' },
              { name: 'Saturday' },
              { name: 'Sunday' },
            ],
          },
          desc_day: {
            sibling_radio: 'how_frequent',
            sibling_radio_value: 'Other',
            name: 'Description',
            type: 'text',
            value: '',
            error: false,
            required: false,
            multiline: true,
          },
          paid_orientation: {
            name: 'Paid orientation?',
            type: 'radio',
            value: '',
            error: false,
            required: true,
            data: ['Yes', 'No'],
          },
          desc_paid: {
            sibling_radio: 'paid_orientation',
            sibling_radio_value: 'Yes',
            name: 'Description',
            type: 'text',
            value: '',
            error: false,
            required: false,
            multiline: true,
          },
          travel_provided: {
            name: 'Travel provided',
            type: 'radio',
            value: '',
            error: false,
            required: true,
            data: ['Yes', 'No'],
          },
          select_travel_provided: {
            sibling_radio: 'travel_provided',
            sibling_radio_value: 'Yes',
            name: 'Travel provided',
            type: 'select',
            value: '',
            error: false,
            required: true,
            optionLabel: 'name',
            optionValue: 'name',
            arrayData: [
              { name: 'Rental car' },
              { name: 'Flight ticket' },
              { name: 'Bus' },
              { name: 'Train' },
            ],
          },
          require: {
            name: 'Do you require: deposits, escrows or hold extra pay checks?',
            type: 'radio',
            value: '',
            error: false,
            required: true,
            data: ['Yes', 'No'],
          },
          desc_require: {
            sibling_radio: 'require',
            sibling_radio_value: 'Yes',
            name: 'Description',
            type: 'text',
            value: '',
            error: false,
            required: false,
            multiline: true,
          },
          home_time: {
            name: 'What is home time for drivers?',
            type: 'select',
            value: '',
            error: false,
            required: false,
            optionLabel: 'name',
            optionValue: 'name',
            arrayData: [
              { name: 'Every weekend' },
              { name: 'Every 2nd week' },
              { name: 'Every 3rd week' },
              { name: 'Every 4th week' },
              { name: 'Other' },
            ],
          },
        },
      },
      cargo: {
        name: 'Cargo Information',
        subgroup: null,
        data: {
          dedicated: {
            name: 'Any dedicated freight?',
            type: 'radio',
            value: '',
            error: false,
            required: false,
            data: ['Yes', 'No'],
          },
          desc_dedicated: {
            sibling_radio: 'dedicated',
            sibling_radio_value: 'Yes',
            name: 'Description',
            type: 'text',
            value: '',
            error: false,
            required: false,
            multiline: true,
          },
          drop_hook: {
            name: 'Any drop & hook?',
            type: 'radio',
            value: '',
            error: false,
            required: false,
            data: ['Yes', 'No'],
          },
          desc_drop_hook: {
            sibling_radio: 'drop_hook',
            sibling_radio_value: 'Yes',
            name: 'Description',
            type: 'text',
            value: '',
            error: false,
            required: false,
            multiline: true,
          },
        },
      },
      support: {
        name: 'Support Info',
        subgroup: {
          files: {
            name: 'Files',
            data: {
              upload_cv: {
                name: 'Upload resume',
                type: 'file',
                value: '',
                error: false,
                required: false,
              },
            },
          },
        },
        data: {
          support_line: {
            name: 'Do you have 24/7 support line?',
            type: 'radio',
            value: '',
            error: false,
            required: false,
            data: ['Yes', 'No'],
          },
          repair_shop: {
            name: 'Do you have a repair shop?',
            type: 'radio',
            value: '',
            error: false,
            required: false,
            data: ['Yes', 'No'],
          },
          provide_fuel: {
            name: 'Do you provide fuel cards?',
            type: 'radio',
            value: '',
            error: false,
            required: false,
            data: ['Yes', 'No'],
          },
          desc_fuel: {
            sibling_radio: 'provide_fuel',
            sibling_radio_value: 'Yes',
            name: 'Description',
            type: 'text',
            value: '',
            error: false,
            required: false,
            multiline: true,
          },
        },
      },
    },
  },
  step3: {
    name: 'Compensation',
    groups: {
      compensation_information: {
        name: 'Compensation Information',
        subgroup: {
          w2_company_driver: {
            parent_select: 'compensation_for',
            name: 'W2 Company Driver',
            data: {
              occupational_select: {
                name: 'Compensation type',
                type: 'select',
                value: '',
                error: false,
                required: false,
                optionLabel: 'name',
                optionValue: 'name',
                multiple: true,
                arrayData: [
                  { name: 'Cpm' },
                  { name: 'Flat rate' },
                  { name: '% from Gross' },
                  { name: 'per/hr' },
                ],
              },
              desc_cpm: {
                sibling_select: 'occupational_select',
                name: 'Description Cpm',
                type: 'text',
                value: '',
                error: false,
                required: false,
                multiline: true,
              },
              desc_flat_rate: {
                sibling_select: 'occupational_select',
                name: 'Description Flat rate',
                type: 'text',
                value: '',
                error: false,
                required: false,
                multiline: true,
              },
              desc_from_gros: {
                sibling_select: 'occupational_select',
                name: 'Description % from Gross',
                type: 'text',
                value: '',
                error: false,
                required: false,
                multiline: true,
              },
              desc_per_hr: {
                sibling_select: 'occupational_select',
                name: 'Description per/hr',
                type: 'text',
                value: '',
                error: false,
                required: false,
                multiline: true,
              },
            },
          },
          independent_contractor: {
            parent_select: 'compensation_for',
            name: '1099 Independent Contractor(IC)',
            data: {
              occupational_select: {
                name: 'Compensation type',
                type: 'select',
                value: '',
                error: false,
                required: false,
                multiple: true,
                optionLabel: 'name',
                optionValue: 'name',
                arrayData: [
                  { name: 'Cpm' },
                  { name: 'Flat rate' },
                  { name: '% from Gross' },
                  { name: 'per/hr' },
                ],
              },
              desc_cpm: {
                sibling_select: 'occupational_select',
                name: 'Description Cpm',
                type: 'text',
                value: '',
                error: false,
                required: false,
                multiline: true,
              },

              desc_flat_rate: {
                sibling_select: 'occupational_select',
                name: 'Description Flat rate',
                type: 'text',
                value: '',
                error: false,
                required: false,
                multiline: true,
              },
              desc_from_gros: {
                sibling_select: 'occupational_select',
                name: 'Description % from Gross',
                type: 'text',
                value: '',
                error: false,
                required: false,
                multiline: true,
              },
              desc_per_hr: {
                sibling_select: 'occupational_select',
                name: 'Description Per/Hr',
                type: 'text',
                value: '',
                error: false,
                required: false,
                multiline: true,
              },
            },
          },
          w2_team: {
            parent_select: 'compensation_for',
            name: 'W2 Team',
            data: {
              occupational_select: {
                name: 'Compensation type',
                type: 'select',
                value: '',
                error: false,
                required: false,
                multiple: true,
                optionLabel: 'name',
                optionValue: 'name',
                arrayData: [
                  { name: 'Cpm' },
                  { name: 'Flat rate' },
                  { name: '% from Gross' },
                  { name: 'per/hr' },
                ],
              },
              desc_cpm: {
                sibling_select: 'occupational_select',
                name: 'Description Cpm',
                type: 'text',
                value: '',
                error: false,
                required: false,
                multiline: true,
              },
              desc_flat_rate: {
                sibling_select: 'occupational_select',
                name: 'Description Flat rate',
                type: 'text',
                value: '',
                error: false,
                required: false,
                multiline: true,
              },
              desc_from_gros: {
                sibling_select: 'occupational_select',
                name: 'Description % from Gross',
                type: 'text',
                value: '',
                error: false,
                required: false,
                multiline: true,
              },
              desc_per_hr: {
                sibling_select: 'occupational_select',
                name: 'Description Per/Hr',
                type: 'text',
                value: '',
                error: false,
                required: false,
                multiline: true,
              },
            },
          },
          team_ic: {
            parent_select: 'compensation_for',
            name: '1099 Team IC',
            data: {
              occupational_select: {
                name: 'Compensation type',
                type: 'select',
                value: '',
                error: false,
                required: false,
                multiple: true,
                optionLabel: 'name',
                optionValue: 'name',
                arrayData: [
                  { name: 'Cpm' },
                  { name: 'Flat rate' },
                  { name: '% from Gross' },
                  { name: 'per/hr' },
                ],
              },
              desc_cpm: {
                sibling_select: 'occupational_select',
                name: 'Description Cpm',
                type: 'text',
                value: '',
                error: false,
                required: false,
                multiline: true,
              },
              desc_flat_rate: {
                sibling_select: 'occupational_select',
                name: 'Description Flat rate',
                type: 'text',
                value: '',
                error: false,
                required: false,
                multiline: true,
              },
              desc_from_gros: {
                sibling_select: 'occupational_select',
                name: 'Description % from Gross',
                type: 'text',
                value: '',
                error: false,
                required: false,
                multiline: true,
              },
              desc_per_hr: {
                sibling_select: 'occupational_select',
                name: 'Description Per/Hr',
                type: 'text',
                value: '',
                error: false,
                required: false,
                multiline: true,
              },
            },
          },
          owner_operator: {
            parent_select: 'compensation_for',
            name: 'Owner Operator',
            data: {
              from_gross: {
                name: '% from Gross',
                type: 'text',
                value: '',
                error: false,
                required: false,
              },
              cargo: {
                name: 'Cargo insurance included in %',
                type: 'radio',
                value: '',
                error: false,
                required: false,
                data: ['Yes', 'No'],
              },
              trailer: {
                name: 'Trailer rent included in %',
                type: 'radio',
                value: '',
                error: false,
                required: false,
                data: ['Yes', 'No'],
              },
              occupational: {
                name: 'Occupational Accident Insurance Cost',
                type: 'text',
                value: '',
                error: false,
                required: false,
              },
              occupational_select: {
                name: 'Occupational Accident Insurance Period',
                type: 'select',
                value: '',
                error: false,
                required: false,
                optionLabel: 'name',
                optionValue: 'name',
                arrayData: [{ name: 'Per week' }, { name: 'Per month' }],
              },
              eld: {
                name: 'ELD',
                type: 'text',
                value: '',
                error: false,
                required: false,
              },
              eld_period: {
                name: 'ELD Period',
                type: 'select',
                value: '',
                error: false,
                required: false,
                optionLabel: 'name',
                optionValue: 'name',
                arrayData: [{ name: 'Per week' }, { name: 'Per month' }],
              },
              provide_pre_pass: {
                name: 'Do you provide Pre pass?',
                type: 'radio',
                value: '',
                error: false,
                required: false,
                data: ['Yes', 'No'],
              },
              pre_pass: {
                name: 'Pre Pass cost',
                type: 'text',
                value: '',
                error: false,
                required: false,
              },
              pre_pass_period: {
                name: 'Pre Pass Period',
                type: 'select',
                value: '',
                error: false,
                required: false,
                optionLabel: 'name',
                optionValue: 'name',
                arrayData: [{ name: 'Per week' }, { name: 'Per month' }],
              },
              weekly_miles: {
                name: 'Average weekly miles',
                type: 'text',
                value: '',
                error: false,
                required: false,
              },
              weekly_gross: {
                name: 'Average weekly Gross',
                type: 'text',
                value: '',
                error: false,
                required: false,
              },
              other_charges: {
                name: 'Other charges',
                type: 'text',
                value: '',
                error: false,
                required: false,
              },
            },
          },
          lease: {
            parent_select: 'compensation_for',
            name: 'Lease',
            data: {
              from_gross: {
                name: '% from Gross',
                type: 'text',
                value: '',
                error: false,
                required: false,
              },
              cargo: {
                name: 'Cargo insurance included in %',
                type: 'radio',
                value: '',
                error: false,
                required: false,
                data: ['Yes', 'No'],
              },
              cargo_insurance_cost: {
                sibling_radio: 'cargo',
                sibling_radio_value: 'No',
                name: 'Cargo Insurance cost',
                type: 'text',
                value: '',
                error: false,
                required: false,
              },
              cargo_insurance_period: {
                sibling_radio: 'cargo',
                sibling_radio_value: 'No',
                name: 'Cargo Insurance Period',
                type: 'select',
                value: '',
                error: false,
                required: false,
                optionLabel: 'name',
                optionValue: 'name',
                arrayData: [{ name: 'Per week' }, { name: 'Per month' }],
              },
              trailer: {
                name: 'Trailer rent included in %',
                type: 'radio',
                value: '',
                error: false,
                required: false,
                data: ['Yes', 'No'],
              },
              trailer_cost: {
                sibling_radio: 'trailer',
                sibling_radio_value: 'No',
                name: 'Trailer rent cost',
                type: 'text',
                value: '',
                error: false,
                required: false,
              },
              trailer_period: {
                sibling_radio: 'trailer',
                sibling_radio_value: 'No',
                name: 'Trailer rent Period',
                type: 'select',
                value: '',
                error: false,
                required: false,
                optionLabel: 'name',
                optionValue: 'name',
                arrayData: [{ name: 'Per week' }, { name: 'Per month' }],
              },
              occupational: {
                name: 'Occupational Accident Insurance Cost',
                type: 'text',
                value: '',
                error: false,
                required: false,
              },
              occupational_select: {
                name: 'Occupational Accident Insurance Period',
                type: 'select',
                value: '',
                error: false,
                required: false,
                optionLabel: 'name',
                optionValue: 'name',
                arrayData: [{ name: 'Per week' }, { name: 'Per month' }],
              },
              eld: {
                name: 'ELD',
                type: 'text',
                value: '',
                error: false,
                required: false,
              },
              eld_period: {
                name: 'ELD Period',
                type: 'select',
                value: '',
                error: false,
                required: false,
                optionLabel: 'name',
                optionValue: 'name',
                arrayData: [{ name: 'Per week' }, { name: 'Per month' }],
              },
              provide_pre_pass: {
                name: 'Do you provide Pre pass?',
                type: 'radio',
                value: '',
                error: false,
                required: false,
                data: ['Yes', 'No'],
              },
              pre_pass: {
                sibling_radio: 'provide_pre_pass',
                sibling_radio_value: 'Yes',
                name: 'Pre Pass cost',
                type: 'text',
                value: '',
                error: false,
                required: false,
              },
              pre_pass_period: {
                sibling_radio: 'provide_pre_pass',
                sibling_radio_value: 'Yes',
                name: 'Pre Pass Period',
                type: 'select',
                value: '',
                error: false,
                required: false,
                optionLabel: 'name',
                optionValue: 'name',
                arrayData: [{ name: 'Per week' }, { name: 'Per month' }],
              },
              weekly_miles: {
                name: 'Average weekly miles',
                type: 'text',
                value: '',
                error: false,
                required: false,
              },
              weekly_gross: {
                name: 'Average weekly Gross',
                type: 'text',
                value: '',
                error: false,
                required: false,
              },
              other_charges: {
                name: 'Other charges',
                type: 'text',
                value: '',
                error: false,
                required: false,
              },
            },
          },
          lease_purchase: {
            parent_select: 'compensation_for',
            name: 'Lease Purchase',
            data: {
              from_gross: {
                name: '% from Gross',
                type: 'text',
                value: '',
                error: false,
                required: false,
              },
              cargo: {
                name: 'Cargo insurance included in %',
                type: 'radio',
                value: '',
                error: false,
                required: false,
                data: ['Yes', 'No'],
              },
              cargo_insurance_cost: {
                sibling_radio: 'cargo',
                sibling_radio_value: 'No',
                name: 'Cargo Insurance cost',
                type: 'text',
                value: '',
                error: false,
                required: false,
              },
              cargo_insurance_period: {
                sibling_radio: 'cargo',
                sibling_radio_value: 'No',
                name: 'Cargo Insurance Period',
                type: 'select',
                value: '',
                error: false,
                required: false,
                optionLabel: 'name',
                optionValue: 'name',
                arrayData: [{ name: 'Per week' }, { name: 'Per month' }],
              },
              trailer: {
                name: 'Trailer rent included in %',
                type: 'radio',
                value: '',
                error: false,
                required: false,
                data: ['Yes', 'No'],
              },
              trailer_cost: {
                sibling_radio: 'trailer',
                sibling_radio_value: 'No',
                name: 'Trailer rent cost',
                type: 'text',
                value: '',
                error: false,
                required: false,
              },
              trailer_period: {
                sibling_radio: 'trailer',
                sibling_radio_value: 'No',
                name: 'Trailer rent Period',
                type: 'select',
                value: '',
                error: false,
                required: false,
                optionLabel: 'name',
                optionValue: 'name',
                arrayData: [{ name: 'Per week' }, { name: 'Per month' }],
              },
              occupational: {
                name: 'Occupational Accident Insurance Cost',
                type: 'text',
                value: '',
                error: false,
                required: false,
              },
              occupational_select: {
                name: 'Occupational Accident Insurance Period',
                type: 'select',
                value: '',
                error: false,
                required: false,
                optionLabel: 'name',
                optionValue: 'name',
                arrayData: [{ name: 'Per week' }, { name: 'Per month' }],
              },
              eld: {
                name: 'ELD',
                type: 'text',
                value: '',
                error: false,
                required: false,
              },
              eld_period: {
                name: 'ELD Period',
                type: 'select',
                value: '',
                error: false,
                required: false,
                optionLabel: 'name',
                optionValue: 'name',
                arrayData: [{ name: 'Per week' }, { name: 'Per month' }],
              },
              provide_pre_pass: {
                name: 'Do you provide Pre pass?',
                type: 'radio',
                value: '',
                error: false,
                required: false,
                data: ['Yes', 'No'],
              },
              pre_pass: {
                sibling_radio: 'provide_pre_pass',
                sibling_radio_value: 'Yes',
                name: 'Pre Pass cost',
                type: 'text',
                value: '',
                error: false,
                required: false,
              },
              pre_pass_period: {
                sibling_radio: 'provide_pre_pass',
                sibling_radio_value: 'Yes',
                name: 'Pre Pass Period',
                type: 'select',
                value: '',
                error: false,
                required: false,
                optionLabel: 'name',
                optionValue: 'name',
                arrayData: [{ name: 'Per week' }, { name: 'Per month' }],
              },
              weekly_miles: {
                name: 'Average weekly miles',
                type: 'text',
                value: '',
                error: false,
                required: false,
              },
              weekly_gross: {
                name: 'Average weekly Gross',
                type: 'text',
                value: '',
                error: false,
                required: false,
              },
              other_charges: {
                name: 'Other charges',
                type: 'text',
                value: '',
                error: false,
                required: false,
              },
            },
          },
          w2_local: {
            parent_select: 'compensation_for',
            name: 'W2 Local',
            data: {
              occupational_select: {
                name: 'Compensation type',
                type: 'select',
                value: '',
                error: false,
                required: false,
                optionLabel: 'name',
                optionValue: 'name',
                multiple: true,
                arrayData: [
                  { name: 'Cpm' },
                  { name: 'Flat rate' },
                  { name: '% from Gross' },
                  { name: 'per/hr' },
                ],
              },
              desc_cpm: {
                sibling_select: 'occupational_select',
                name: 'Description Cpm',
                type: 'text',
                value: '',
                error: false,
                required: false,
                multiline: true,
              },
              desc_flat_rate: {
                sibling_select: 'occupational_select',
                name: 'Description Flat rate',
                type: 'text',
                value: '',
                error: false,
                required: false,
                multiline: true,
              },
              desc_from_gros: {
                sibling_select: 'occupational_select',
                name: 'Description % from Gross',
                type: 'text',
                value: '',
                error: false,
                required: false,
                multiline: true,
              },
              desc_per_hr: {
                sibling_select: 'occupational_select',
                name: 'Description Per/Hr',
                type: 'text',
                value: '',
                error: false,
                required: false,
                multiline: true,
              },
            },
          },
          local_1099: {
            parent_select: 'compensation_for',
            name: '1099 Local',
            data: {
              occupational_select: {
                name: 'Compensation type',
                type: 'select',
                value: '',
                error: false,
                required: false,
                optionLabel: 'name',
                optionValue: 'name',
                multiple: true,
                arrayData: [
                  { name: 'Cpm' },
                  { name: 'Flat rate' },
                  { name: '% from Gross' },
                  { name: 'per/hr' },
                ],
              },
              desc_cpm: {
                sibling_select: 'occupational_select',
                name: 'Description Cpm',
                type: 'text',
                value: '',
                error: false,
                required: false,
                multiline: true,
              },
              desc_flat_rate: {
                sibling_select: 'occupational_select',
                name: 'Description Flat rate',
                type: 'text',
                value: '',
                error: false,
                required: false,
                multiline: true,
              },
              desc_from_gros: {
                sibling_select: 'occupational_select',
                name: 'Description % from Gross',
                type: 'text',
                value: '',
                error: false,
                required: false,
                multiline: true,
              },
              desc_per_hr: {
                sibling_select: 'occupational_select',
                name: 'Description Per/Hr',
                type: 'text',
                value: '',
                error: false,
                required: false,
                multiline: true,
              },
            },
          },
          students: {
            parent_select: 'compensation_for',
            name: 'Students',
            data: {
              occupational_select: {
                name: 'Compensation type',
                type: 'select',
                value: '',
                error: false,
                required: false,
                optionLabel: 'name',
                optionValue: 'name',
                multiple: true,
                arrayData: [
                  { name: 'Cpm' },
                  { name: 'Flat rate' },
                  { name: '% from Gross' },
                  { name: 'per/hr' },
                ],
              },
              desc_flat_rate: {
                sibling_select: 'occupational_select',
                name: 'Description Flat rate',
                type: 'text',
                value: '',
                error: false,
                required: false,
                multiline: true,
              },
              desc_from_gros: {
                sibling_select: 'occupational_select',
                name: 'Description % from Gross',
                type: 'text',
                value: '',
                error: false,
                required: false,
                multiline: true,
              },
              desc_per_hr: {
                sibling_select: 'occupational_select',
                name: 'Description Per/Hr',
                type: 'text',
                value: '',
                error: false,
                required: false,
                multiline: true,
              },
            },
          },
        },
        data: {
          compensation_for: {
            name: 'Compensation for',
            type: 'select',
            value: '',
            error: false,
            required: false,
            multiple: true,
            optionLabel: 'name',
            optionValue: 'name',
            arrayData: [
              { name: 'W2 Company Driver' },
              { name: '1099 Independent Contractor(IC)' },
              { name: 'W2 Team' },
              { name: '1099 Team IC' },
              { name: 'Owner Operator' },
              { name: 'Lease' },
              { name: 'Lease Purchase' },
              { name: 'W2 Local' },
              { name: '1099 Local' },
              { name: 'Students' },
            ],
          },
        },
      },
    },
  },
  step2: {
    name: 'Carrier Hiring Criteria',
    groups: {
      employee_information: {
        name: 'Employee Information',
        subgroup: null,
        data: {
          equipment_type: {
            name: 'Equipment Type',
            type: 'select',
            value: '',
            error: false,
            required: true,
            multiple: true,
            optionLabel: 'name',
            optionValue: 'name',
            arrayData: [
              { name: 'Dry Van' },
              { name: 'Reefer' },
              { name: 'Flatbed' },
              { name: 'Tanker' },
              { name: 'Intermodal' },
              { name: 'Auto Hauler' },
              { name: 'Step deck' },
              { name: 'Other' },
            ],
          },
          driver_type: {
            name: 'Driver Type',
            type: 'select',
            value: '',
            error: false,
            required: true,
            multiple: true,
            optionLabel: 'name',
            optionValue: 'name',
            arrayData: [
              { name: 'W2 Company driver' },
              { name: '1099 Independent Contractor (IC)' },
              { name: 'W2 Team' },
              { name: '1099 Team IC' },
              { name: 'Owner Operator' },
              { name: 'Lease' },
              { name: 'Lease Purchase' },
              { name: 'W2 Local' },
              { name: '1099 Local' },
              { name: 'Students' },
            ],
          },
          how_many_drivers: {
            name: 'How many drivers do you need currently?',
            type: 'text',
            value: '',
            error: false,
            required: true,
          },
          minimum_experience_required: {
            name: 'Minimum experience required',
            type: 'select',
            value: '',
            error: false,
            required: true,
            multiple: true,
            optionLabel: 'name',
            optionValue: 'name',
            arrayData: [
              { name: 'none' },
              { name: '1-5 months' },
              { name: '6-11 months' },
              { name: '1 year' },
              { name: '2 years' },
              { name: '3 years' },
              { name: '4+ years' },
            ],
          },
          required_endorsements: {
            name: 'Required Endorsements',
            type: 'radio',
            value: '',
            error: false,
            required: false,
            data: ['Yes', 'No'],
          },
          select_required_endorsements: {
            sibling_radio: 'required_endorsements',
            sibling_radio_value: 'Yes',
            name: 'Required Endorsements',
            type: 'select',
            value: '',
            error: false,
            required: false,
            multiple: true,
            optionLabel: 'name',
            optionValue: 'name',
            arrayData: [
              { name: 'H-Hazmat' },
              { name: 'N-Tank Vehicle' },
              { name: 'T-Double/triple trailers' },
              { name: 'X-Tank+Hazardous' },
            ],
          },
          hiring_location: {
            name: 'Hiring Location by',
            type: 'select',
            value: '',
            error: false,
            required: false,
            multiple: true,
            optionLabel: 'name',
            optionValue: 'name',
            arrayData: [
              { name: 'Alabama', abbreviation: 'AL' },
              { name: 'Alaska', abbreviation: 'AK' },
              { name: 'Arizona', abbreviation: 'AZ' },
              { name: 'Arkansas', abbreviation: 'AR' },
              { name: 'California', abbreviation: 'CA' },
              { name: 'Colorado', abbreviation: 'CO' },
              { name: 'Connecticut', abbreviation: 'CT' },
              { name: 'Delaware', abbreviation: 'DE' },
              { name: 'Florida', abbreviation: 'FL' },
              { name: 'Georgia', abbreviation: 'GA' },
              { name: 'Hawaii', abbreviation: 'HI' },
              { name: 'Idaho', abbreviation: 'ID' },
              { name: 'Illinois', abbreviation: 'IL' },
              { name: 'Indiana', abbreviation: 'IN' },
              { name: 'Iowa', abbreviation: 'IA' },
              { name: 'Kansas', abbreviation: 'KS' },
              { name: 'Kentucky', abbreviation: 'KY' },
              { name: 'Louisiana', abbreviation: 'LA' },
              { name: 'Maine', abbreviation: 'ME' },
              { name: 'Maryland', abbreviation: 'MD' },
              { name: 'Massachusetts', abbreviation: 'MA' },
              { name: 'Michigan', abbreviation: 'MI' },
              { name: 'Minnesota', abbreviation: 'MN' },
              { name: 'Mississippi', abbreviation: 'MS' },
              { name: 'Missouri', abbreviation: 'MO' },
              { name: 'Montana', abbreviation: 'MT' },
              { name: 'Nebraska', abbreviation: 'NE' },
              { name: 'Nevada', abbreviation: 'NV' },
              { name: 'New Hampshire', abbreviation: 'NH' },
              { name: 'New Jersey', abbreviation: 'NJ' },
              { name: 'New Mexico', abbreviation: 'NM' },
              { name: 'New York', abbreviation: 'NY' },
              { name: 'North Carolina', abbreviation: 'NC' },
              { name: 'North Dakota', abbreviation: 'ND' },
              { name: 'Ohio', abbreviation: 'OH' },
              { name: 'Oklahoma', abbreviation: 'OK' },
              { name: 'Oregon', abbreviation: 'OR' },
              { name: 'Pennsylvania', abbreviation: 'PA' },
              { name: 'Rhode Island', abbreviation: 'RI' },
              { name: 'South Carolina', abbreviation: 'SC' },
              { name: 'South Dakota', abbreviation: 'SD' },
              { name: 'Tennessee', abbreviation: 'TN' },
              { name: 'Texas', abbreviation: 'TX' },
              { name: 'Utah', abbreviation: 'UT' },
              { name: 'Vermont', abbreviation: 'VT' },
              { name: 'Virginia', abbreviation: 'VA' },
              { name: 'Washington', abbreviation: 'WA' },
              { name: 'West Virginia', abbreviation: 'WV' },
              { name: 'Wisconsin', abbreviation: 'WI' },
              { name: 'Wyoming', abbreviation: 'WY' },
            ],
          },
        },
      },
      equipment_information: {
        name: 'Equipment Information',
        subgroup: null,
        data: {
          equipment_information: {
            name: 'Equipment Information',
            type: 'radio',
            value: '',
            error: false,
            required: false,
            data: ['Yes', 'No'],
          },
          what_trucks: {
            sibling_radio: 'equipment_information',
            sibling_radio_value: 'Yes',
            name: 'What trucks do you have?',
            type: 'select',
            value: '',
            error: false,
            required: false,
            multiple: true,
            optionLabel: 'name',
            optionValue: 'name',
            arrayData: [
              { name: 'Freightliner' },
              { name: 'Volvo' },
              { name: 'Peterbilt' },
              { name: 'Kenworth' },
              { name: 'Western Star' },
              { name: 'International' },
              { name: '4+ years' },
            ],
          },
          transmission: {
            sibling_radio: 'equipment_information',
            sibling_radio_value: 'Yes',
            name: 'Transmission',
            type: 'select',
            value: '',
            error: false,
            required: false,
            multiple: true,
            optionLabel: 'name',
            optionValue: 'name',
            arrayData: [{ name: 'Automatic' }, { name: 'Manual' }],
          },
          do_your_trucks_have: {
            sibling_radio: 'equipment_information',
            sibling_radio_value: 'Yes',
            name: 'Do your trucks have',
            type: 'select',
            value: '',
            error: false,
            required: false,
            multiple: true,
            optionLabel: 'name',
            optionValue: 'name',
            arrayData: [
              { name: 'Inverter' },
              { name: 'APU units' },
              { name: 'Fridge' },
              { name: 'Microwave' },
              { name: 'Driver facing cameras' },
              { name: 'Crash mitigation' },
            ],
          },
          max_speed: {
            sibling_radio: 'equipment_information',
            sibling_radio_value: 'Yes',
            name: 'What is max speed of trucks?',
            type: 'text',
            value: '',
            error: false,
            required: true,
          },
          year_of_trucks: {
            sibling_radio: 'equipment_information',
            sibling_radio_value: 'Yes',
            name: 'Year of trucks',
            type: 'text',
            value: '',
            error: false,
            required: false,
          },
        },
      },
      benefits: {
        name: 'Benefits',
        subgroup: null,
        data: {
          offer_benefits: {
            name: 'Do you offer benefits?',
            type: 'radio',
            value: '',
            error: false,
            required: false,
            data: ['Yes', 'No'],
          },
          describe: {
            sibling_radio: 'offer_benefits',
            sibling_radio_value: 'Yes',
            name: 'Describe',
            type: 'text',
            value: '',
            error: false,
            required: false,
            multiline: true,
          },
          which_benefits: {
            sibling_radio: 'offer_benefits',
            sibling_radio_value: 'Yes',
            name: 'Which benefits you offer?',
            type: 'select',
            value: '',
            error: false,
            required: false,
            multiple: true,
            optionLabel: 'name',
            optionValue: 'name',
            arrayData: [
              { name: 'Vision Benefits' },
              { name: 'Dental Benefits' },
              { name: 'Retirement benefits' },
              { name: 'Sign on bonus' },
              { name: 'Any safety' },
              { name: 'Layover Pay' },
              { name: 'Breakdown Pay' },
              { name: 'Pay Loading/unloading' },
              { name: 'Pay extra pick up' },
              { name: 'Health Insurance' },
            ],
          },
        },
      },
      offense: {
        name: 'Offense',
        subgroup: null,
        data: {
          drivers_with_tickets: {
            name: 'Will you consider drivers with tickets or accidents?',
            type: 'radio',
            value: '',
            error: false,
            required: false,
            data: ['Yes', 'No'],
          },
          max_number_of_preentable: {
            sibling_radio: 'drivers_with_tickets',
            sibling_radio_value: 'Yes',
            name: 'Max number of preventable accidents in the past 3 years?',
            type: 'select',
            value: '',
            error: false,
            required: false,

            optionLabel: 'name',
            optionValue: 'name',
            arrayData: [
              { name: '1' },
              { name: '2' },
              { name: '3' },
              { name: '4' },
              { name: '5' },
              { name: '6' },
              { name: '7' },
              { name: '8' },
              { name: '9' },
              { name: '10' },
            ],
          },
          max_number_of_moving: {
            sibling_radio: 'drivers_with_tickets',
            sibling_radio_value: 'Yes',
            name: 'Max number of moving violations in the past 3 years?',
            type: 'select',
            value: '',
            error: false,
            required: false,

            optionLabel: 'name',
            optionValue: 'name',
            arrayData: [
              { name: '1' },
              { name: '2' },
              { name: '3' },
              { name: '4' },
              { name: '5' },
              { name: '6' },
              { name: '7' },
              { name: '8' },
              { name: '9' },
              { name: '10' },
            ],
          },
          drivers_with_criminal: {
            name: 'Allow drivers with criminal record?',
            type: 'radio',
            value: '',
            error: false,
            required: false,
            data: ['Yes', 'No'],
          },
          sap_programs: {
            name: 'Allow drivers with SAP Programs?',
            type: 'radio',
            value: '',
            error: false,
            required: false,
            data: ['Yes', 'No'],
          },
          dui_dwi: {
            name: 'Allow drivers with pending/convicted DUI or DWI charges?',
            type: 'radio',
            value: '',
            error: false,
            required: false,
            data: ['Yes', 'No'],
          },
        },
      },
      additional_information: {
        name: 'Additional Information',
        subgroup: null,
        data: {
          allow_pets: {
            name: 'Allow pets?',
            type: 'radio',
            value: '',
            error: false,
            required: false,
            data: ['Yes', 'No'],
          },
          pet_policy: {
            sibling_radio: 'allow_pets',
            sibling_radio_value: 'Yes',
            name: 'What is your pet policy?',
            type: 'text',
            value: '',
            error: false,
            required: false,
          },
          rider_policy: {
            name: 'Do you have a Rider Policy?',
            type: 'radio',
            value: '',
            error: false,
            required: false,
            data: ['Yes', 'No'],
          },
          indicate_minimum_age: {
            sibling_radio: 'rider_policy',
            sibling_radio_value: 'Yes',
            name: 'Please, indicate minimum age',
            type: 'text',
            value: '',
            error: false,
            required: true,
          },
        },
      },
    },
  },
}

export default CARRIER_FORM
